### ISSUE TITLE
SyntaxError: Non-UTF-8 code starting with '\xd7' in file aptsources-cleanup.zip

### ISSUE THREAD

**Issue by PePoDev** [davidfoerster/aptsources-cleanup#24] opened 2020-02-06 17:59 UTC
Full error message
```console
File "aptsources-cleanup.zip", line 1
SyntaxError: Non-UTF-8 code starting with '\xd7' in file aptsources-cleanup.zip on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
python version: python3
Ubuntu version: 18.04 LTS

**Comment by davidfoerster** [comment] 2020-02-06 22:00
This looks like the same underlying issue as #23 and the same questions and recommendations apply:

> What’s the output of `type -a python3` and `/usr/bin/python3 --version`?
> 
> `aptsources-cleanup` only works (well) with the Python installation shipped together with your Linux distribution, i. e. Ubuntu, although this particular error doesn’t seem related to the usual issue of a missing or incompatible `apt` module.

**Comment by PePoDev** [comment] 2020-02-07 12:16
type -a python3
> python3 is /usr/bin/python3

/usr/bin/python3 --version
> Python 3.6.9

**Comment by davidfoerster** [comment] 2020-02-07 12:32
Hmm… Did you install a different Python package? What’s the output of `dpkg-query -S /usr/bin/python3 | awk -F ': ' '!a[$1]++{print $1}' | xargs -r -- apt-cache policy --`?

**Comment by PePoDev** [comment] 2020-02-07 13:00
I'm not sure, But this is result og your command.
```console
python3-minimal:
  Installed: 3.6.7-1~18.04
  Candidate: 3.6.7-1~18.04
  Version table:
 *** 3.6.7-1~18.04 500
        500 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.6.5-3 500
        500 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages
```

**Comment by davidfoerster** [comment] 2020-02-07 13:08
Looks fine. That’s the Python package shipped by Canonical which means I can’t understand why it works for me but not you.

Quoting myself from #23:

> This is really weird. Python should detect ZIP bundles automagically and run them as such (there isn’t even a command-line option to specify the input format explicitly). However your Python interpreter tries to run the ZIP bundle like a regular source code file.
>
> ---
>
> In the mean time you can download the source code and run it as described in [README](https://github.com/davidfoerster/aptsources-cleanup/blob/master/README.md#usage).

In the mean time I’m flagging this as *wontfix* because I have absolutely no idea why this happens and can’t reproduce it. If anybody has any ideas I’m all ears.

**Comment by PePoDev** [comment] 2020-02-07 18:34
OMG.

The problem is happen because I download zip file on Windows and transfer it via WinSCP.
When I try to download zip file with wget on linux it work fine.

Thanks you very much.
And sorry for lowy detail.

**Closed as completed** 2020-02-07 18:37 UTC
Labels: invalid

**Comment by davidfoerster** [comment] 2020-02-08 00:30
That’s an interesting hint! Can you please perform a checksum on the file downloaded via WinSCP and/or attach the entire (apparently) bogus file to your comment here?

For reference, here’s what I get:
```
$ md5sum aptsources-cleanup.zip
2d97c7e13ed52993d4a8460c2127e6de  aptsources-cleanup.zip
$ python3 -OEs aptsources-cleanup.zip --version
aptsources-cleanup.zip, version 0.1.6.6 2019-10-27 6306f12:master
```

**Comment by PePoDev** [comment] 2020-02-08 06:12
```console
$ python3 -OEs aptsources-cleanup.zip --version
aptsources-cleanup.zip, version 0.1.6.6 2019-10-27 6306f12:master

$ python3 -OEs aptsources-cleanup-winscp.zip --version
File "aptsources-cleanup-winscp.zip", line 1
SyntaxError: Non-UTF-8 code starting with '\xd7' in file aptsources-cleanup-winscp.zip on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

$ md5sum aptsources-cleanup.zip
2d97c7e13ed52993d4a8460c2127e6de  aptsources-cleanup.zip

$ md5sum aptsources-cleanup-winscp.zip
f3b44fbcd0a33628b19c8a1460b18ed3  aptsources-cleanup-winscp.zip
```

**Comment by davidfoerster** [comment] 2020-02-08 12:22
There you go. My guess: WinSCP has a “text” mode that translates new-line character sequences between Windows and Unix during file transfers. It’s possible that somebody or something selected text mode for this file transfer.

**Comment by PePoDev** [comment] 2020-02-08 20:24
You right.
When I change to binary mode It's work fine.

That is my human error. 😂
