### ISSUE TITLE
False negative duplicate matches with HTTP/HTTPS

### ISSUE THREAD

**Issue by njacquemin** [davidfoerster/aptsources-cleanup#26] opened 2020-04-11 12:55 UTC
Hi !

I did this : `sudo python3 -OEs aptsources-cleanup.zip`
But the result was quite disturbing : `No duplicate entries were found.`
I did a `sudo apt-get update` just before the command and here's the result : 

![screenshot](https://user-images.githubusercontent.com/11017930/79044263-6dad2a80-7c04-11ea-8fb7-8bf28f9a116e.png)

**Comment by davidfoerster** [comment] 2020-04-12 10:23
Thanks for your bug report! Could you please provide

 1. the content of all the files mentioned in the above terminal output so that I can reproduce the issue and
 2. provide the above terminal content as text instead of an image? You can either select and copy and paste the terminal content or [capture the command output using stream redirection](https://askubuntu.com/q/335770/175814).

Thanks.

**Comment by njacquemin** [comment] 2020-04-12 14:35
Well, I have unchecked the vs-code package (`https://packages.microsoft.com/repos/vscode stable main`) via the GUI and... I don't have errors/warnings anymore. When I recheck that package, all the errors come back.

Here's the terminal output :
```
➜  Downloads sudo apt update                                     
Get:1 http://ubuntu.mirrors.ovh.net/ubuntu bionic InRelease [242 kB]
Ign:2 http://dl.google.com/linux/chrome/deb stable InRelease                                                                            
Hit:3 http://ppa.launchpad.net/amanusk/python-s-tui/ubuntu bionic InRelease                                                             
Ign:4 https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 InRelease                                                              
Hit:5 https://deb.nodesource.com/node_10.x bionic InRelease                                                                             
Hit:6 http://dl.google.com/linux/chrome/deb stable Release                                                                              
Get:7 http://ubuntu.mirrors.ovh.net/ubuntu bionic-backports InRelease [74,6 kB]                                                         
Get:8 http://ubuntu.mirrors.ovh.net/ubuntu bionic-security InRelease [88,7 kB]                                                          
Hit:9 http://ppa.launchpad.net/freecad-maintainers/freecad-stable/ubuntu bionic InRelease                                               
Hit:10 http://ppa.launchpad.net/kivy-team/kivy/ubuntu bionic InRelease                                                                  
Ign:11 http://binaries.erlang-solutions.com/debian bionic InRelease                                                                     
Ign:12 https://mkvtoolnix.download/ubuntu bionic InRelease                                                                              
Hit:13 https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 Release                                                               
Ign:14 https://dl.packager.io/srv/deb/opf/openproject/stable/9/ubuntu 18.04 InRelease                                                   
Hit:15 https://dl.yarnpkg.com/debian stable InRelease                                                                                   
Hit:16 http://ppa.launchpad.net/libretro/stable/ubuntu bionic InRelease                                                                 
Hit:17 http://binaries.erlang-solutions.com/debian bionic Release                                                                       
Ign:18 http://repo.vivaldi.com/stable/deb stable InRelease                                                                              
Hit:19 https://mkvtoolnix.download/ubuntu bionic Release                                                                                
Hit:20 https://packages.microsoft.com/repos/vscode stable InRelease                                                                     
Hit:21 http://repo.vivaldi.com/stable/deb stable Release                                                                                
Hit:22 https://brave-browser-apt-release.s3.brave.com stable InRelease                                                                  
Hit:23 http://ppa.launchpad.net/linuxuprising/java/ubuntu bionic InRelease                     
Hit:24 http://ppa.launchpad.net/lutris-team/lutris/ubuntu bionic InRelease
Hit:25 http://ppa.launchpad.net/oguzhaninan/stacer/ubuntu bionic InRelease                                  
Hit:26 http://ppa.launchpad.net/olive-editor/olive-editor/ubuntu bionic InRelease                           
Get:27 https://dl.packager.io/srv/deb/opf/openproject/stable/9/ubuntu 18.04 Release [1.221 B]
Hit:29 http://ppa.launchpad.net/teejee2008/ppa/ubuntu bionic InRelease                
Hit:30 http://ppa.launchpad.net/ubuntu-x-swat/updates/ubuntu bionic InRelease
Hit:31 http://ppa.launchpad.net/xorg-edgers/ppa/ubuntu bionic InRelease
Hit:32 http://ppa.launchpad.net/zeal-developers/ppa/ubuntu bionic InRelease             
Fetched 407 kB in 4s (112 kB/s)                                                         
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:49 and /etc/apt/sources.list.d/vscode.list:3
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:49 and /etc/apt/sources.list.d/vscode.list:3
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:49 and /etc/apt/sources.list.d/vscode.list:3
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:49 and /etc/apt/sources.list.d/vscode.list:3
W: Target DEP-11 (main/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list:49 and /etc/apt/sources.list.d/vscode.list:3
W: Target DEP-11 (main/dep11/Components-all.yml) is configured multiple times in /etc/apt/sources.list:49 and /etc/apt/sources.list.d/vscode.list:3
W: Target DEP-11-icons-small (main/dep11/icons-48x48.tar) is configured multiple times in /etc/apt/sources.list:49 and /etc/apt/sources.list.d/vscode.list:3
W: Target DEP-11-icons (main/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list:49 and /etc/apt/sources.list.d/vscode.list:3
W: Target CNF (main/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list:49 and /etc/apt/sources.list.d/vscode.list:3
W: Target CNF (main/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list:49 and /etc/apt/sources.list.d/vscode.list:3
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:49 and /etc/apt/sources.list.d/vscode.list:3
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:49 and /etc/apt/sources.list.d/vscode.list:3
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:49 and /etc/apt/sources.list.d/vscode.list:3
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:49 and /etc/apt/sources.list.d/vscode.list:3
W: Target DEP-11 (main/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list:49 and /etc/apt/sources.list.d/vscode.list:3
W: Target DEP-11 (main/dep11/Components-all.yml) is configured multiple times in /etc/apt/sources.list:49 and /etc/apt/sources.list.d/vscode.list:3
W: Target DEP-11-icons-small (main/dep11/icons-48x48.tar) is configured multiple times in /etc/apt/sources.list:49 and /etc/apt/sources.list.d/vscode.list:3
W: Target DEP-11-icons (main/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list:49 and /etc/apt/sources.list.d/vscode.list:3
W: Target CNF (main/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list:49 and /etc/apt/sources.list.d/vscode.list:3
W: Target CNF (main/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list:49 and /etc/apt/sources.list.d/vscode.list:3
```

And I join the files.
[sourceslists.zip](https://github.com/davidfoerster/aptsources-cleanup/files/4466481/sourceslists.zip)

**Comment by davidfoerster** [comment] 2020-04-15 00:41
Duplicate of #20 although I still made a change to the default behaviour now that I saw how APT behaves. See the last comment(s) there for details.

**Closed as completed by davidfoerster** 2020-04-15 00:41 UTC
Labels: duplicate
