### ISSUE TITLE
Ubuntu PPAs

### ISSUE THREAD

**Issue by ghost** [davidfoerster/aptsources-cleanup#2] opened 2018-04-08 16:04 UTC
Hello,
in bash, I get messages from apt such as:
"Target xxx is configured multiple times in /etc/apt/sources.list.d/xxx"
..but script says "No duplicate entries were found."
Can you please update the script to include PPA sources? I use Kubuntu 17.10 and it has multiple PPA sources lists in /etc/apt/sources.list.d/*.list. Main sources.list is located in /etc/apt/sources.list.
Thanks!

**Comment by davidfoerster** [comment] 2018-04-08 19:51
Hi, could you please attach the full list of errors, warnings and notices of Apt (prefixed with `E:`, `W:` and `N:` respectively in English) as well as the content of all sources files mentioned therein. This would help me reproduce and trace down the issue. Thanks!

**Comment by ghost** [comment] 2018-04-09 00:45
Hi, I have an install script which adds ppas and then installs packages. The problem occurs when it runs for more than one time. (OK I know there should be no reason to run such script repeatedly.) When I was writing it, I expected apt to just skip adding already existing sources similar way like when I try to install already installed or remove nonexisting packages, but it adds sources multiple times instead. Anyway, I attached the script, bash output and all sources lists. I also noticed strange thing in lists containing duplicates - original url source path has trailing slash at the end, the other does not. Maybe this could be the problem that two lines have same meaning but strings itselves are not equal? Thanks!
[script-report.zip](https://github.com/davidfoerster/apt-remove-duplicate-source-entries/files/1888099/script-report.zip)

**Comment by davidfoerster** [comment] 2018-04-10 14:01
Looks like `add-apt-repository` doesn't normalize path names. I hadn't even thought of that.

Fixed in f7f2b8e550050ad1ffc5fa20f5a5e90d8c909851.

**Closed as completed by davidfoerster** 2018-04-10 14:01 UTC
Labels: bug
